# Generated by Django 5.0.2 on 2026-04-18 05:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityCheckRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=50, unique=True, verbose_name='ID правила')),
                ('name', models.CharField(max_length=200, verbose_name='Название правила')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Критический'), ('HIGH', 'Высокий'), ('MEDIUM', 'Средний'), ('WARNING', 'Предупреждение'), ('INFO', 'Информационный')], max_length=20, verbose_name='Критичность')),
                ('check_logic', models.TextField(verbose_name='Логика проверки')),
                ('remediation_template', models.TextField(verbose_name='Шаблон рекомендации')),
                ('responsibility', models.CharField(choices=[('provider', 'Поставщик'), ('consumer', 'Потребитель'), ('shared', 'Совместная')], default='consumer', max_length=20, verbose_name='Ответственность')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включено')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Правило проверки',
                'verbose_name_plural': 'Правила проверки',
                'ordering': ['category', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='TestDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название набора')),
                ('dataset_type', models.CharField(choices=[('STORAGE', 'Хранилища'), ('IAM', 'Права доступа'), ('SLA', 'SLA провайдера'), ('ENCRYPTION', 'Шифрование')], max_length=20, verbose_name='Тип данных')),
                ('description', models.TextField(verbose_name='Описание')),
                ('test_data', models.JSONField(verbose_name='Тестовые данные')),
                ('expected_results', models.JSONField(default=dict, verbose_name='Ожидаемые результаты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тестовый набор данных',
                'verbose_name_plural': 'Тестовые наборы данных',
                'ordering': ['dataset_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TestProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_number', models.CharField(max_length=50, unique=True, verbose_name='Номер протокола')),
                ('test_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата тестирования')),
                ('tester_name', models.CharField(default='Студент', max_length=100, verbose_name='Тестировщик')),
                ('status', models.CharField(choices=[('SUCCESS', 'Успешно'), ('WARNING', 'С предупреждениями'), ('FAILED', 'Провален'), ('IN_PROGRESS', 'В процессе')], default='IN_PROGRESS', max_length=20, verbose_name='Статус')),
                ('total_checks', models.IntegerField(default=0, verbose_name='Всего проверок')),
                ('passed_checks', models.IntegerField(default=0, verbose_name='Пройдено проверок')),
                ('failed_checks', models.IntegerField(default=0, verbose_name='Провалено проверок')),
                ('risk_score', models.FloatField(default=0.0, verbose_name='Оценка риска')),
                ('compliance_percent', models.FloatField(default=0.0, verbose_name='Процент соответствия')),
                ('detailed_results', models.JSONField(default=dict, verbose_name='Детальные результаты')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('test_duration', models.FloatField(default=0.0, verbose_name='Длительность теста (сек)')),
            ],
            options={
                'verbose_name': 'Протокол тестирования',
                'verbose_name_plural': 'Протоколы тестирования',
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='SecurityFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=200, verbose_name='Ресурс')),
                ('resource_type', models.CharField(max_length=50, verbose_name='Тип ресурса')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Критический'), ('HIGH', 'Высокий'), ('MEDIUM', 'Средний'), ('WARNING', 'Предупреждение'), ('INFO', 'Информационный')], max_length=20, verbose_name='Критичность')),
                ('finding_message', models.TextField(verbose_name='Описание находки')),
                ('remediation', models.TextField(verbose_name='Рекомендации по устранению')),
                ('responsibility', models.CharField(choices=[('provider', 'Поставщик'), ('consumer', 'Потребитель'), ('shared', 'Совместная')], max_length=20, verbose_name='Ответственность')),
                ('detection_time', models.DateTimeField(auto_now_add=True, verbose_name='Время обнаружения')),
                ('resolved', models.BooleanField(default=False, verbose_name='Устранено')),
                ('resolution_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата устранения')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='security_checker.testprotocol', verbose_name='Протокол')),
            ],
            options={
                'verbose_name': 'Находка безопасности',
                'verbose_name_plural': 'Находки безопасности',
                'ordering': ['-severity', '-detection_time'],
            },
        ),
    ]
